# Generated by Django 2.1.7 on 2019-03-02 17:54

from django.db import migrations, models  # pragma: no cover


class Migration(migrations.Migration):  # pragma: no cover

    dependencies = [  # pragma: no cover
        ('api', '0001_initial'),
    ]

    operations = [  # pragma: no cover
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
