# Generated by Django 2.1.7 on 2019-03-03 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contabilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contabilidade',
            options={'ordering': ['nome'], 'verbose_name': 'Contabilidade', 'verbose_name_plural': 'Contabilidades'},
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
